[features]
seeds = false
skip-lint = false
[programs.devnet]
bsl_swap = "2kK95sc8qHyHQbyEHADvxC3uwB2kvLLajuqajh1cF27R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/noyan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
