[features]
seeds = false
skip-lint = false
[programs.mainnet]
bsl_swap = "FLjoHCAmjojgt7DUxid7WR9EyEj2Pysq9cMehRiM5vtp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/noyan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
