[features]
seeds = false
skip-lint = false
[programs.devnet]
bsl_swap = "BtUAJPzuyRQddsr6D8KV1MXDBS6iev6e2J1doExiLRQf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/noyan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
